-- AlterTable
ALTER TABLE `post` ADD COLUMN `authorId` INTEGER NULL,
    ADD COLUMN `postType` ENUM('ADMIN', 'USER') NOT NULL DEFAULT 'ADMIN',
    MODIFY `status` ENUM('ACTIVE', 'INACTIVE', 'PENDING') NOT NULL DEFAULT 'ACTIVE';

-- AddForeignKey
ALTER TABLE `Post` ADD CONSTRAINT `Post_authorId_fkey` FOREIGN KEY (`authorId`) REFERENCES `User`(`id`) ON DELETE SET NULL ON UPDATE CASCADE;
